# Generated by Django 4.1.6 on 2023-02-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
    ]
