# Generated by Django 4.1.6 on 2023-02-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0002_alter_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
